"""Post-hoc statistics over an arbitrary subset of the results store.

Filters the store's canonical result rows (global results.csv) by experiment,
config id, IV values, and/or trial indices, recomputes the full statistical
analysis (LMM / Friedman+Nemenyi / Spearman) plus loss tables, and writes
``analysis_summary.md``.

If you request a trial range that hasn't been run yet, instead of silently
computing partial stats it writes a runnable ``run_missing.sh`` that extends the
relevant experiments to fill the gap.

Examples:
    # Stats over everything in the store
    python analyze.py

    # One experiment, only GRU + MHTA archs, cot >= 0.5
    python analyze.py --experiment grid_search --arch GRU,MHTA --set cot=0.5,0.7

    # Two specific configs by global id
    python analyze.py --config-id cfg_a3f9d2c4,cfg_0b7e11ff

    # Require 10 trials; emit run_missing.sh if fewer exist
    python analyze.py --experiment grid_search --trials 0-9

    # A sandbox store
    python analyze.py --results-root sandbox/my_test
"""
import argparse
import os

from .internal import registry
from .experiment import write_summary_md


# ----------------------------------------------------------------------------
# Filtering helpers (shared with view.py)
# ----------------------------------------------------------------------------
def parse_int_set(spec: str) -> set:
    """Parse '0-4,7' → {0,1,2,3,4,7}."""
    out = set()
    for part in spec.split(','):
        part = part.strip()
        if not part:
            continue
        if '-' in part:
            lo, hi = part.split('-')
            out.update(range(int(lo), int(hi) + 1))
        else:
            out.add(int(part))
    return out


def resolve_col(key: str, sample_row: dict):
    """Map an IV short name (or explicit column) to its results.csv column."""
    if key in sample_row:
        return key
    for sub in ('data', 'model', 'train'):
        col = f'config_{sub}_{key}'
        if col in sample_row:
            return col
    return None


def apply_value_filters(rows, *, experiments=None, config_ids=None, arch=None,
                        set_specs=None, where_specs=None, config_idxs=None):
    """Apply everything except the trial filter; returns the filtered rows."""
    if not rows:
        return rows
    set_specs = set_specs or {}
    where_specs = where_specs or {}

    def keep(row):
        if experiments and str(row.get('experiment')) not in experiments:
            return False
        if config_ids and str(row.get('config_id')) not in config_ids:
            return False
        if arch:
            col = resolve_col('arch', row)
            if col is None or str(row.get(col)) not in arch:
                return False
        for key, vals in set_specs.items():
            col = resolve_col(key, row)
            if col is None or str(row.get(col)) not in vals:
                return False
        for col, vals in where_specs.items():
            if str(row.get(col)) not in vals:
                return False
        if config_idxs is not None and row.get('config_idx') not in config_idxs:
            return False
        return True

    return [r for r in rows if keep(r)]


def infer_ivs(results_root, experiments=None):
    """Gather IV keys + ordinal IVs from the registry's experiment entries
    (authoritative), optionally restricted to a set of experiment names.
    Returns (ivs_dict, ordinal_list)."""
    ivs, ordinal = {}, set()
    for e in registry.load_registry(results_root)['experiments']:
        if experiments and e.get('name') not in experiments:
            continue
        for k in e.get('ivs', {}):
            ivs.setdefault(k, [])
        ordinal.update(e.get('ordinal_ivs', []))
    return ivs, sorted(ordinal)


# ----------------------------------------------------------------------------
# Missing-cell detection → run_missing.sh
# ----------------------------------------------------------------------------
def find_missing(scope_rows, requested_trials):
    """Per (experiment, config_id), which requested trials are absent.

    Returns {experiment_name: max_needed_trial_count}."""
    present = {}
    for r in scope_rows:
        present.setdefault((r.get('experiment'), r.get('config_id')), set()).add(r.get('trial_idx'))
    needed = {}
    for (exp, _cfg), trials in present.items():
        missing = requested_trials - trials
        if missing:
            needed[exp] = max(needed.get(exp, 0), max(requested_trials) + 1)
    return needed


def write_missing_script(path, needed, results_root):
    lines = ["#!/usr/bin/env bash",
             "# Auto-generated by analyze.py: extend experiments to cover the",
             "# requested trials, then re-run the same analyze.py command.",
             "set -e", ""]
    for exp, target in sorted(needed.items()):
        lines.append(f"python experiment.py --name {exp} "
                     f"--results-root {results_root} --trials {target}")
    with open(path, 'w') as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)


# ----------------------------------------------------------------------------
def add_filter_args(parser):
    """Register the shared subset-filter CLI flags (also used by view.py)."""
    parser.add_argument('--results-root', default='results',
                        help="Results store root (default: results).")
    parser.add_argument('--experiment', default=None,
                        help="Comma-separated experiment names to keep.")
    parser.add_argument('--config-id', dest='config_ids', default=None,
                        help="Comma-separated global config ids to keep (e.g. cfg_a3f9d2c4).")
    parser.add_argument('--arch', default=None, help="Comma-separated architectures to keep.")
    parser.add_argument('--set', dest='set_specs', action='append', default=[],
                        help="Keep rows where IV in given values: key=v1,v2 (repeatable).")
    parser.add_argument('--where', dest='where_specs', action='append', default=[],
                        help="Keep rows where column==values: col=v1,v2 (repeatable, exact column).")
    parser.add_argument('--config-idx', default=None,
                        help="Comma/range set of per-experiment config indices to keep.")
    parser.add_argument('--trials', default=None,
                        help="Trial index set to require/keep (e.g. 0-9). Drives missing-cell detection.")


def filter_store_rows(args):
    """Load the store's rows and apply all CLI filters.

    Returns (scope_rows, subset_rows, experiments_set, requested_trials): scope
    has the value filters applied; subset additionally applies the trial filter."""
    rows = registry.load_results(args.results_root)
    if not rows:
        raise SystemExit(f"No result rows found in '{args.results_root}'.")

    experiments = set(args.experiment.split(',')) if args.experiment else None
    config_ids = set(args.config_ids.split(',')) if args.config_ids else None
    arch = set(args.arch.split(',')) if args.arch else None
    set_specs = {}
    for spec in args.set_specs:
        key, _, vals = spec.partition('=')
        set_specs[key.strip()] = set(vals.split(','))
    where_specs = {}
    for spec in args.where_specs:
        col, _, vals = spec.partition('=')
        where_specs[col.strip()] = set(vals.split(','))
    config_idxs = parse_int_set(args.config_idx) if args.config_idx else None
    requested_trials = parse_int_set(args.trials) if args.trials else None

    scope = apply_value_filters(rows, experiments=experiments, config_ids=config_ids,
                                arch=arch, set_specs=set_specs,
                                where_specs=where_specs, config_idxs=config_idxs)
    if requested_trials is not None:
        subset = [r for r in scope if r.get('trial_idx') in requested_trials]
    else:
        subset = scope

    print(f"Loaded {len(rows)} rows → {len(subset)} after filters "
          f"({len({r.get('config_id') for r in subset})} configs).")
    return scope, subset, experiments, requested_trials


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    add_filter_args(parser)
    parser.add_argument('--out', default=None,
                        help="Output markdown path (default: <results-root>/analysis_summary.md).")
    parser.add_argument('--no-emit-missing', action='store_true',
                        help="Report missing cells but do not write run_missing.sh.")
    args = parser.parse_args()

    scope, subset, experiments, requested_trials = filter_store_rows(args)

    # Missing-cell detection.
    if requested_trials is not None:
        needed = find_missing(scope, requested_trials)
        if needed:
            print("\n⚠ Requested trials are missing for some configs:")
            for exp, target in sorted(needed.items()):
                print(f"   {exp}: needs {target} trials")
            if not args.no_emit_missing:
                script = os.path.join(args.results_root, 'run_missing.sh')
                write_missing_script(script, needed, args.results_root)
                print(f"\n→ Wrote {script}. Run it, then re-run this analyze.py command.")
            return

    if not subset:
        raise SystemExit("Filtered subset is empty; nothing to analyze.")

    ivs, ordinal = infer_ivs(args.results_root, experiments)
    out = args.out or os.path.join(args.results_root, 'analysis_summary.md')
    write_summary_md(out, subset, ivs, ordinal,
                     output_root=args.results_root,
                     title="Post-hoc Analysis", include_dir_structure=False)
    print(f"✓ Analysis written to '{out}'")


if __name__ == '__main__':
    main()
